/**
 * Lagonoy, Camarines Sur barangay festivities from DAHOM Lagonoy.
 */
export const LAGONOY_FIESTA_SCHEDULE = [
  { barangay: "Omalo", date: "April 15" },
  { barangay: "Gimagtocon", date: "April 22" },
  { barangay: "Kinahologan", date: "April 25" },
  { barangay: "San Francisco (Pob.)", date: "May 1" },
  { barangay: "San Isidro Norte (Pob.)", date: "May 1" },
  { barangay: "San Isidro Sur (Pob.)", date: "May 1" },
  { barangay: "San Vicente (Pob.)", date: "May 1" },
  { barangay: "Santa Maria (Pob.)", date: "May 1" },
  { barangay: "Saripongpong (Pob.)", date: "May 1" },
  { barangay: "Olas", date: "May 5" },
  { barangay: "Mapid", date: "May 8" },
  { barangay: "Panagan", date: "May 8" },
  { barangay: "Binanuahan", date: "May 9" },
  { barangay: "Santa Cruz (Pob.)", date: "May 10" },
  { barangay: "Himanag", date: "May 12" },
  { barangay: "Bocogan", date: "May 15" },
  { barangay: "Sipaco", date: "May 15" },
  { barangay: "Ginorangan (Genorangan)", date: "May 16" },
  { barangay: "San Isidro", date: "May 16" },
  { barangay: "Balaton", date: "May 19" },
  { barangay: "Dahat", date: "May 21" },
  { barangay: "San Sebastian", date: "May 23" },
  { barangay: "Agosais", date: "May 26" },
  { barangay: "Amoguis", date: "May 29" },
  { barangay: "Cabotonan", date: "May 29" },
  { barangay: "Guibahoy", date: "June 1" },
  { barangay: "Panicuan", date: "June 8" },
  { barangay: "Pinamihagan", date: "June 13" },
  { barangay: "Manamoc", date: "June 14" },
  { barangay: "Gubat", date: "June 15" },
  { barangay: "Loho", date: "June 16" },
  { barangay: "Burabod", date: "July 3" },
  { barangay: "Del Carmen", date: "July 16" },
  { barangay: "Mangogon", date: "August 10" },
  { barangay: "San Roque", date: "August 16" },
  { barangay: "San Ramon", date: "August 31" },
  { barangay: "San Rafael", date: "October 24" },
  { barangay: "Agpo-Camagong-Tabog", date: "May 17" },
];
