/**
 * City of Malolos 2023 Ecological Profile, Table EcS-37: Fiestas.
 */
export const MALOLOS_FIESTA_SCHEDULE = [
  { barangay: "Anilao", date: "May 3", patronSaint: "Santa Cruz" },
  { barangay: "Atlag", date: "June 13", patronSaint: "San Antonio de Padua" },
  { barangay: "Bagna", date: "May 3", patronSaint: "Santa Cruz" },
  { barangay: "Bagong Bayan", date: "November 17", patronSaint: "Santa Isabel" },
  { barangay: "Balite", date: "May 10", patronSaint: "Santa Cruz" },
  { barangay: "Balayong", date: "First Sunday of May", patronSaint: "Santa Cruz" },
  { barangay: "Barihan", date: "9th Sunday after Easter", patronSaint: "Santisima Trinidad" },
  { barangay: "Bulihan", date: "May 15", patronSaint: "San Isidro Labrador" },
  { barangay: "Bungahan", date: "Third Sunday of January", patronSaint: "Santo Nino" },
  { barangay: "Caingin", date: "August 24", patronSaint: "San Bartolome" },
  { barangay: "Calero", date: "First Sunday of May", patronSaint: "Santa Cruz" },
  { barangay: "Canalate", date: "January 23", patronSaint: "San Ildefonso" },
  { barangay: "Catmon", date: "January 20", patronSaint: "San Sebastian" },
  { barangay: "Cofradia", date: "May 15", patronSaint: "San Isidro Labrador" },
  { barangay: "Dakila", date: "May 3", patronSaint: "Santa Cruz" },
  { barangay: "Guinhawa", date: "Last Sunday of November", patronSaint: "Nuestra Senora de los Remedios" },
  { barangay: "Caliligawan", date: "December 13", patronSaint: "Santa Lucia" },
  { barangay: "Liyang", date: "Third Saturday of May", patronSaint: "Santa Cruz" },
  { barangay: "Ligas", date: "November 22", patronSaint: "Nuestra Senora de los Remedios" },
  { barangay: "Longos", date: "May 1", patronSaint: "San Jose" },
  { barangay: "Look 1st", date: "Last Sunday of April", patronSaint: "Santo Rosario" },
  { barangay: "Look 2nd", date: "May 12", patronSaint: "Santo Cristo" },
  { barangay: "Lugam", date: "Last Sunday of April", patronSaint: "Santo Rosario" },
  { barangay: "Mabolo", date: "October 4", patronSaint: "San Francisco de Asis" },
  { barangay: "Mambog", date: "August 16", patronSaint: "San Roque" },
  { barangay: "Masile", date: "November 22", patronSaint: "Nuestra Senora Virgen de los Remedios" },
  { barangay: "Matimbo", date: "May 15", patronSaint: "San Isidro Labrador" },
  { barangay: "Mojon", date: "November 30", patronSaint: "San Andres" },
  { barangay: "Namayan", date: "December 13", patronSaint: "Santa Lucia" },
  { barangay: "Niugan", date: "First Sunday of May", patronSaint: "Santa Cruz" },
  { barangay: "Pamarawan", date: "April 24", patronSaint: "Stella Maris" },
  { barangay: "Panasahan", date: "May 1", patronSaint: "San Jose" },
  { barangay: "Pinagbakahan", date: "9th Sunday after Easter", patronSaint: "Santisima Trinidad" },
  { barangay: "San Agustin", date: "Last Sunday of August", patronSaint: "San Agustin" },
  { barangay: "San Gabriel", date: "September 29", patronSaint: "San Gabriel" },
  { barangay: "San Juan", date: "June 24", patronSaint: "San Juan Bautista" },
  { barangay: "San Pablo", date: "January 25", patronSaint: "San Pablo" },
  { barangay: "Santiago", date: "July 25", patronSaint: "Santiago Apostol" },
  { barangay: "Santisima Trinidad", date: "9th Sunday after Easter", patronSaint: "Santisima Trinidad" },
  { barangay: "Santo Cristo", date: "Second Sunday of May", patronSaint: "Santo Cristo" },
  { barangay: "Santo Niño (Pob.)", date: "Last Sunday of January", patronSaint: "Santo Nino" },
  { barangay: "Santol", date: "August 10", patronSaint: "San Lorenzo Diakono" },
  { barangay: "Santo Rosario (Pob.)", date: "Third Saturday of October", patronSaint: "Santo Rosario" },
  { barangay: "San Vicente (Pob.)", date: "April 5", patronSaint: "San Vicente Ferrer" },
  { barangay: "Sumapang Bata", date: "October 1", patronSaint: "Santa Teresita" },
  { barangay: "Sumapang Matanda", date: "First Sunday of May", patronSaint: "Santa Cruz" },
  { barangay: "Taal", date: "December 27", patronSaint: "San Juan Evangelista" },
  { barangay: "Tikay", date: "June 29", patronSaint: "San Pedro Apostol" },
];
