/**
 * Miagao, Iloilo — barangay feast days from verified LGU/parish/community sources.
 * Town poblacion barangays share the municipal patronal fiesta (Sept 22).
 * Source: miagao.gov.ph municipal ordinance (Santo Tomas de Villanueva).
 * Bacauan: miagao.gov.ph barangay profile (San Roque, Aug 16).
 * Banbanan: LGU profile (fiesta every January, month-only).
 * Holy Child Parish / on-day FB-YouTube posts for Sto. Niño parish barangays.
 * Cubay: Our Lady of the Miraculous Medal Parish patronal fiesta (Nov 27).
 * miagao.tripod.com/barangays/*.htm barangay profile feast schedules.
 */
const MIAGAO_POB_BARANGAYS = [
  "Baybay Norte (Pob.)",
  "Baybay Sur (Pob.)",
  "Bolho (Pob.)",
  "Mat-Y (Pob.)",
  "Tacas (Pob.)",
  "Ubos Ilawod (Pob.)",
  "Ubos Ilaya (Pob.)",
];

export const MIAGAO_FIESTA_ENTRIES = [
  ...MIAGAO_POB_BARANGAYS.map((barangay) => ({
    barangay,
    municipality: "Miagao",
    month: 9,
    dayStart: 22,
    patronSaint: "Santo Tomas de Villanueva",
    dateSource: "lgu-miagao-gov-ph",
  })),
  {
    barangay: "Bacauan",
    municipality: "Miagao",
    month: 8,
    dayStart: 16,
    patronSaint: "San Roque",
    dateSource: "lgu-miagao-gov-ph",
  },
  {
    barangay: "Banbanan",
    municipality: "Miagao",
    month: 1,
    datePrecision: "month",
    dateSource: "lgu-miagao-gov-ph",
    note: "LGU profile: observes barangay fiesta every January (no day given)",
  },
  {
    barangay: "Igbugo",
    municipality: "Miagao",
    month: 1,
    dayStart: 15,
    patronSaint: "Señor Sto. Niño",
    dateSource: "curated-online-miagao-holy-child-parish-fb",
    note: "On-day Happy Fiesta Jan 14–15 (2025); parish proclaimed on barangay fiesta Jan 15",
  },
  {
    barangay: "Naclub",
    municipality: "Miagao",
    month: 4,
    dayStart: 19,
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy Fiesta Brgy. Naclub posts (Apr 19, 2022 and 2024)",
  },
  {
    barangay: "Cawayanan",
    municipality: "Miagao",
    month: 2,
    dayStart: 7,
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy Fiesta Barangay Cawayanan video (Feb 7, 2026)",
  },
  {
    barangay: "Igsoligue",
    municipality: "Miagao",
    month: 2,
    dayStart: 22,
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy Fiesta Brgy. Igsoligue video (Feb 22, 2025)",
  },
  {
    barangay: "Fundacion",
    municipality: "Miagao",
    month: 12,
    dayStart: 28,
    patronSaint: "Nuestra Señora de los Remedios",
    dateSource: "curated-online-miagao-fb",
    note: "On-day HAPPY FIESTA BRGY. FUNDACION post (Dec 28, 2025)",
  },
  {
    barangay: "Tigbagacay",
    municipality: "Miagao",
    month: 12,
    dayStart: 27,
    dayEnd: 28,
    patronSaint: "Nuestra Señora de Guia",
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy Fiesta Brgy. Tigbagacay (Dec 27–28, 2024–2025)",
  },
  {
    barangay: "Cubay",
    municipality: "Miagao",
    month: 11,
    dayStart: 27,
    patronSaint: "Our Lady of the Miraculous Medal",
    dateSource: "parish-our-lady-of-miraculous-medal-cubay-miagao",
    note: "Parish patronal fiesta Nov 27 (Miraculous Medal Parish, Cubay)",
  },
  {
    barangay: "Cabalaunan",
    municipality: "Miagao",
    month: 8,
    dayStart: 16,
    patronSaint: "San Roque",
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy patronal fiesta Brgy. Cabalaunan (Aug 16, 2025)",
  },
  {
    barangay: "Bacolod",
    municipality: "Miagao",
    month: 1,
    dayStart: 9,
    patronSaint: "Black Nazarene",
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy Fiesta Jan 7–10 (2025) and Jan 8 (2026); patron Jesus Nazareno",
  },
  {
    barangay: "Igpandan",
    municipality: "Miagao",
    month: 12,
    dayStart: 25,
    dayEnd: 26,
    patronSaint: "The Holy Family",
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy Fiesta Dec 25–26 (2025)",
  },
  {
    barangay: "Potrido",
    municipality: "Miagao",
    month: 10,
    dayStart: 28,
    dateSource: "curated-online-miagao-fb",
    note: "On-day HAPPY FIESTA Barangay Potrido (Oct 28, 2024–2025)",
  },
  {
    barangay: "Dawog",
    municipality: "Miagao",
    month: 12,
    dayStart: 18,
    dayEnd: 19,
    patronSaint: "Nuestra Señora de Guía",
    dateSource: "curated-online-miagao-fb",
    note: "Patronal fiesta Dec 18–19 (2024); on-day Nuestra Señora de Guía post",
  },
  {
    barangay: "Igdalaquit",
    municipality: "Miagao",
    month: 4,
    dayStart: 10,
    dayEnd: 11,
    dateSource: "curated-online-miagao-fb",
    note: "Hara sang Igdalaquit fiesta program Apr 10–11 (2024)",
  },
  {
    barangay: "Narorogan",
    municipality: "Miagao",
    month: 11,
    dayStart: 27,
    dateSource: "curated-online-miagao-fb",
    note: "On-day HAPPY FIESTA Barangay Narorogan and Cubay (Nov 27, 2023)",
  },
  {
    barangay: "Igdulaca",
    municipality: "Miagao",
    month: 4,
    dayStart: 22,
    patronSaint: "San Vicente Ferrer",
    dateSource: "curated-online-miagao-holy-child-parish-fb",
    note: "On-day Happy Fiesta and coronation program Apr 22 (2026)",
  },
  {
    barangay: "Buenavista Sur",
    municipality: "Miagao",
    month: 2,
    dayStart: 28,
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy Fiesta Brgy. Buenavista Sur (Feb 28, 2026)",
  },
  {
    barangay: "Nam-O Sur",
    municipality: "Miagao",
    month: 2,
    dayStart: 24,
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy-happy Fiesta Barangay Nam-O Sur (Feb 2026)",
  },
  {
    barangay: "Indag-an",
    municipality: "Miagao",
    month: 5,
    dayStart: 13,
    patronSaint: "Our Lady of Fatima",
    dateSource: "curated-online-miagao-fb",
    note: "On-day Happy Fiesta Brgy. Indag-an (May 13, 2024); Miraculous Medal parish",
  },
  {
    barangay: "Ilog-Ilog",
    municipality: "Miagao",
    month: 6,
    dayStart: 29,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Fiesta 2024 ilog-ilog (Jun 29, 2024; joe M WANDERS)",
  },
  {
    barangay: "Pudpud",
    municipality: "Miagao",
    month: 2,
    dayStart: 28,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Sitio Igpaka Brgy. Pudpud (Feb 28, 2025)",
  },
  {
    barangay: "Dalije",
    municipality: "Miagao",
    month: 1,
    dayStart: 27,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Dalije (Jan 27, 2024; Kuya Bim vlog)",
  },
  {
    barangay: "Bagumbayan",
    municipality: "Miagao",
    month: 4,
    dayStart: 28,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Bagumbayan (Apr 28, 2024)",
  },
  {
    barangay: "Kirayan Norte",
    municipality: "Miagao",
    month: 5,
    dayStart: 1,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Kirayan Norte (May 1, 2024)",
  },
  {
    barangay: "Tig-Apog-Apog",
    municipality: "Miagao",
    month: 3,
    dayStart: 24,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Tig-Apog-Apog (Mar 24, 2024)",
  },
  {
    barangay: "Cabunotan",
    municipality: "Miagao",
    month: 4,
    dayStart: 21,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Cabunotan (Apr 21, 2024)",
  },
  {
    barangay: "Agdum",
    municipality: "Miagao",
    month: 4,
    dayStart: 20,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Agdum (Apr 20, 2024)",
  },
  {
    barangay: "Olango",
    municipality: "Miagao",
    month: 4,
    dayStart: 15,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Olango (Apr 15, 2024)",
  },
  {
    barangay: "Oyungan",
    municipality: "Miagao",
    month: 5,
    dayStart: 1,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Oyungan fiesta (May 1; Kuya Bim/MIAGAO IPADAYAW cluster)",
  },
  {
    barangay: "Palaca",
    municipality: "Miagao",
    month: 5,
    dayStart: 16,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO I-PADAYAW Happy Fiesta Barangay Palaca (May 16, 2023; joe M WANDERS)",
  },
  {
    barangay: "Dingle",
    municipality: "Miagao",
    month: 5,
    dayStart: 12,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO IPADAYAW Happy Fiesta Brgy. Dingle (May 12, 2023)",
  },
  {
    barangay: "Buenavista Norte",
    municipality: "Miagao",
    month: 4,
    dayStart: 30,
    patronSaint: "Sta. Rita de Cascia",
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO I-PADAYAW Happy Fiesta Brgy. Buenavista Norte (Apr 30, 2023)",
  },
  {
    barangay: "Kirayan Sur",
    municipality: "Miagao",
    month: 1,
    dayStart: 29,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Kirayan Sur (Jan 29, 2023)",
  },
  {
    barangay: "Saring",
    municipality: "Miagao",
    month: 3,
    dayStart: 31,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy fiesta brgySarin Miagao (Mar 31, 2026)",
  },
  {
    barangay: "Tan-Agan",
    municipality: "Miagao",
    month: 4,
    dayStart: 24,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO IPADAYAW Brgy. Tan-agan (Apr 24, 2023)",
  },
  {
    barangay: "Tigmalapad",
    municipality: "Miagao",
    month: 5,
    dayStart: 4,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Brgy. Tigmalapad Fiesta motovlog (May 4, 2024)",
  },
  {
    barangay: "Igpajo",
    municipality: "Miagao",
    month: 5,
    dayStart: 10,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO IPADAYAW Happy Patronal Fiesta Brgy. Igpajo (May 10, 2023)",
  },
  {
    barangay: "Diday",
    municipality: "Miagao",
    month: 4,
    dayStart: 4,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Adventure in Diday #FiestainDiday (Apr 4, 2021)",
  },
  {
    barangay: "Calampitao",
    municipality: "Miagao",
    month: 5,
    dayStart: 3,
    patronSaint: "Birhen Maria de Salvacion",
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO IPADAYAW Happy Fiesta Brgy. Calampitao (May 3; joe M WANDERS)",
  },
  {
    barangay: "Damilisan",
    municipality: "Miagao",
    month: 4,
    dayStart: 28,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Damilisan Miagao Fiesta with SIRC (Apr 28, 2024)",
  },
  {
    barangay: "Gines",
    municipality: "Miagao",
    month: 4,
    dayStart: 28,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Gines (Apr 28, 2024)",
  },
  {
    barangay: "Igcabito-On",
    municipality: "Miagao",
    month: 4,
    dayStart: 23,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Igcabito-on (Apr 23, 2024)",
  },
  {
    barangay: "Sag-On",
    municipality: "Miagao",
    month: 4,
    dayStart: 27,
    patronSaint: "San Antonio de Padua",
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO IPADAYAW Happy Fiesta Brgy. Sag-on (Apr 27, 2023)",
  },
  {
    barangay: "Ticdalan",
    municipality: "Miagao",
    month: 5,
    dayStart: 6,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO IPADAYAW miyesta sa Brgy. Ticdalan (May 6, 2023)",
  },
  {
    barangay: "Cagbang",
    municipality: "Miagao",
    month: 4,
    dayStart: 29,
    patronSaint: "San Vicente Ferrer",
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO I-PADAYAW Happy Fiesta Brgy. Cagbang (Apr 29, 2023)",
  },
  {
    barangay: "Igbita",
    municipality: "Miagao",
    month: 4,
    dayStart: 22,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Igbita (Apr 22, 2023; joe M WANDERS)",
  },
  {
    barangay: "Tugura-Ao",
    municipality: "Miagao",
    month: 4,
    dayStart: 25,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day MIAGAO IPADAYAW Happy Fiesta Brgy. Tugura-ao (Apr 25, 2023)",
  },
  {
    barangay: "Pungtod Monteclaro",
    municipality: "Miagao",
    month: 3,
    dayStart: 20,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Pungtod Monteclaro (Mar 20, 2026)",
  },
  {
    barangay: "Malagyan",
    municipality: "Miagao",
    month: 4,
    dayStart: 28,
    dateSource: "curated-online-miagao-youtube",
    note: "Last night of fiesta post Apr 27, 2022; patronal day Apr 28",
  },
  {
    barangay: "Mambatad",
    municipality: "Miagao",
    month: 5,
    dayStart: 11,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Happy Fiesta Brgy. Mambatad (May 11, 2025)",
  },
  {
    barangay: "Naulid",
    municipality: "Miagao",
    month: 1,
    dayStart: 16,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Brgy. Naulid Fiesta video (Jan 16, 2017)",
  },
  {
    barangay: "Lanutan",
    municipality: "Miagao",
    month: 7,
    dayStart: 10,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day lanutan fiesta video (Jul 10, 2008)",
  },
  {
    barangay: "Igtuba",
    municipality: "Miagao",
    month: 8,
    dayStart: 3,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Annual Fiesta Brgy. Igbuta/Igtuba (Aug 3, 2022)",
  },
  {
    barangay: "La Consolacion",
    municipality: "Miagao",
    month: 1,
    dayStart: 13,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day happy fiesta Brgy. La Consolacion Miagao (Jan 13, 2023)",
  },
  {
    barangay: "Guibongan",
    municipality: "Miagao",
    month: 6,
    dayStart: 26,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Colorfunrun @ brgy.guibongan Miagao (Jun 26, 2022)",
  },
  {
    barangay: "Onop",
    municipality: "Miagao",
    month: 4,
    dayStart: 10,
    dayEnd: 11,
    dateSource: "curated-online-miagao-youtube",
    note: "Patronal Fiesta Brgy. Onop Apr 10–11 (2013; LIMA Entertainment vlog)",
  },
  {
    barangay: "Maninila",
    municipality: "Miagao",
    month: 8,
    dayStart: 15,
    dayEnd: 16,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Annual Patronal Fiesta Brgy. Maninila (Aug 15–16, 2024)",
  },
  {
    barangay: "Calagtangan",
    municipality: "Miagao",
    month: 4,
    dayStart: 28,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Battle of the Sound Brgy. Calagtangan fiesta (Apr 28, 2018)",
  },
  {
    barangay: "Kirayan Tacas",
    municipality: "Miagao",
    month: 12,
    dayStart: 30,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Kirayan Tacas Fiesta Ride (Dec 30, 2019)",
  },
  {
    barangay: "Banga",
    municipality: "Miagao",
    month: 1,
    dayStart: 7,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Patronal Fiesta24 setup Brgy. Banga (Jan 7, 2024; Divetech Pro Audio)",
  },
  {
    barangay: "Bolocaue",
    municipality: "Miagao",
    month: 4,
    dayStart: 24,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Bolocaue fiesta 101 video (Apr 24, 2019)",
  },
  {
    barangay: "Belen",
    municipality: "Miagao",
    month: 12,
    dayStart: 26,
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/belen.htm: fiesta every Dec 26 (formerly Jan 19 with San Jose)",
  },
  {
    barangay: "Lacadon",
    municipality: "Miagao",
    month: 1,
    dayStart: 26,
    patronSaint: "Señor Sto. Niño",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/lacadon.htm: patronal fiesta every Jan 26",
  },
  {
    barangay: "Tabunacan",
    municipality: "Miagao",
    month: 4,
    dayStart: 23,
    patronSaint: "St. Vincent Ferrer",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/tabunacan.htm: barangay fiesta since Apr 23, 1960",
  },
  {
    barangay: "Lumangan",
    municipality: "Miagao",
    month: 11,
    dayStart: 25,
    patronSaint: "Desposorio",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/lumangan.htm: patron feast Nov 25 (pre-WWII tradition)",
  },
  {
    barangay: "Tig-Amaga",
    municipality: "Miagao",
    month: 4,
    dayStart: 8,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Tig-amaga DH | Redemption | April 8, 2018 (title date; corroborated by FIESTA TIG AMAGA LAAG 2022 upload Mar 13)",
  },
  {
    barangay: "Baraclayan",
    municipality: "Miagao",
    month: 4,
    datePrecision: "month",
    patronSaint: "San Roque",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/baraclayan.htm: fiesta in April (no day given)",
  },
  {
    barangay: "Caitib",
    municipality: "Miagao",
    month: 12,
    dayStart: 8,
    patronSaint: "La Purisima Concepcion",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/caitib.htm: patronal fiesta every Dec 8",
  },
  {
    barangay: "Cubay Ubos",
    municipality: "Miagao",
    month: 10,
    dayStart: 23,
    patronSaint: "Our Lady of the Holy Rosary",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/cubay_ubos.htm: barangay feast Oct 23, 1960 (separated from Cubay)",
  },
  {
    barangay: "Wayang",
    municipality: "Miagao",
    month: 12,
    dayStart: 28,
    dayEnd: 29,
    patronSaint: "Holy Rosary",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/wayang.htm: annual fiesta Dec 28–29",
  },
  {
    barangay: "Matalngon",
    municipality: "Miagao",
    month: 2,
    datePrecision: "month",
    patronSaint: "Nuestra Señora de la Candelaria",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/matalngon.htm: fiesta every February (no day given)",
  },
  {
    barangay: "Cadoldolan",
    municipality: "Miagao",
    month: 12,
    datePrecision: "month",
    patronSaint: "Medalla Milagros",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/cadoldolan.htm: fiesta in December (no day given)",
  },
  {
    barangay: "Tambong",
    municipality: "Miagao",
    month: 2,
    datePrecision: "month",
    patronSaint: "Lady of Lourdes",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/tambong.htm: shares Aguiauan barrio fiesta in February",
  },
  {
    barangay: "Aguiauan",
    municipality: "Miagao",
    month: 2,
    datePrecision: "month",
    patronSaint: "Lady of Lourdes",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/tambong.htm: patroness Lady of Lourdes feast in February",
  },
  {
    barangay: "Maricolcol",
    municipality: "Miagao",
    month: 3,
    datePrecision: "month",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/maricolcol.htm: feast celebrated every March (no day given)",
  },
  {
    barangay: "Tumagboc",
    municipality: "Miagao",
    month: 4,
    datePrecision: "month",
    patronSaint: "Nuestra Señora de Salvacion",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/tumagboc.htm: feast in April (no day given)",
  },
  {
    barangay: "Igcatambor",
    municipality: "Miagao",
    month: 4,
    datePrecision: "month",
    patronSaint: "San Joseph",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/igcatambor.htm: feast of San Joseph in April (no day given)",
  },
  {
    barangay: "Valencia",
    municipality: "Miagao",
    month: 4,
    dayStart: 24,
    patronSaint: "San Vicente Ferrer",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/valencia.htm: transferred from February to Apr 24 (Msgr. Claudio S. Sale era)",
  },
  {
    barangay: "Bariri",
    municipality: "Miagao",
    month: 4,
    datePrecision: "month",
    patronSaint: "St. Anthony",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/bariri.htm: patron St. Anthony honored every April (no day given)",
  },
  {
    barangay: "Tatoy",
    municipality: "Miagao",
    month: 11,
    dayStart: 29,
    dateSource: "curated-online-miagao-youtube",
    note: "On-day Festive Feast: Experiencing Barrio Fiesta in Tatoy, Miagao (Nov 29, 2023 upload)",
  },
  {
    barangay: "Igcabidio",
    municipality: "Miagao",
    month: 12,
    datePrecision: "month",
    patronSaint: "Immaculate Concepcion",
    dateSource: "curated-online-miagao-tripod",
    note: "miagao.tripod.com/barangays/igcabidio.htm: patroness Immaculate Concepcion honored in December (no day given)",
  },
];

/** Movable feast schedules from miagao.tripod.com barangay profiles. */
export const MIAGAO_RELATIVE_FIESTA_SCHEDULE = [
  {
    date: "2nd Saturday of December",
    barangay: "Narat-an",
    municipality: "Miagao",
    patronSaint: "Nuestra Señora de Guia",
    dateSource: "curated-online-miagao-tripod",
  },
  {
    date: "3rd Saturday of November",
    barangay: "Sibucao",
    municipality: "Miagao",
    patronSaint: "Our Lady of Miraculous Medal",
    dateSource: "curated-online-miagao-tripod",
  },
  {
    date: "1st Saturday of December",
    barangay: "Mabayan",
    municipality: "Miagao",
    patronSaint: "San Lorenzo Ruiz",
    dateSource: "curated-online-miagao-tripod",
  },
  {
    date: "Last Saturday of January",
    barangay: "Paro-On",
    municipality: "Miagao",
    patronSaint: "Saint Peter",
    dateSource: "curated-online-miagao-tripod",
  },
];
