/**
 * Mulanay, Quezon — barangay fiesta dates from LGU barangay profiles.
 * Source: https://mulanay.gov.ph/barangays/
 */
export const MULANAY_FIESTA_ENTRIES = [
  {
    barangay: "Amuguis",
    municipality: "Mulanay",
    month: 5,
    dayStart: 15,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "San Isidro Labrador",
  },
  {
    barangay: "Anonang",
    municipality: "Mulanay",
    month: 5,
    dayStart: 15,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "San Isidro Labrador",
  },
  {
    barangay: "Barangay 1 (Pob.)",
    municipality: "Mulanay",
    month: 6,
    dayStart: 29,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "Saint Peter the Apostle",
  },
  {
    barangay: "Barangay 2 (Pob.)",
    municipality: "Mulanay",
    month: 6,
    dayStart: 29,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "Saint Peter the Apostle",
  },
  {
    barangay: "Barangay 3 (Pob.)",
    municipality: "Mulanay",
    month: 6,
    dayStart: 29,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "Saint Peter the Apostle",
  },
  {
    barangay: "Barangay 4 (Pob.)",
    municipality: "Mulanay",
    month: 6,
    dayStart: 29,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "Saint Peter the Apostle",
  },
  {
    barangay: "Bagong Silang",
    municipality: "Mulanay",
    month: 1,
    dayStart: 15,
    dayEnd: 16,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "Sto. Niño",
  },
  {
    barangay: "Ajos",
    municipality: "Mulanay",
    month: 1,
    dayStart: 15,
    dayEnd: 16,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "Sto. Niño",
  },
  {
    barangay: "Burgos",
    municipality: "Mulanay",
    month: 5,
    dayStart: 18,
    dateSource: "lgu-mulanay-gov-ph",
  },
  {
    barangay: "Butanyog",
    municipality: "Mulanay",
    month: 1,
    dayStart: 20,
    dateSource: "lgu-mulanay-gov-ph",
    note: "Sitio Solcom tradition",
  },
  {
    barangay: "F. Nanadiego",
    municipality: "Mulanay",
    month: 6,
    dayStart: 1,
    dayEnd: 2,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "Our Mother of Perpetual Help",
  },
  {
    barangay: "San Isidro",
    municipality: "Mulanay",
    month: 5,
    dayStart: 15,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "San Isidro Labrador",
  },
  {
    barangay: "San Pedro",
    municipality: "Mulanay",
    month: 6,
    dayStart: 28,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "San Pedro",
  },
  {
    barangay: "Santa Rosa",
    municipality: "Mulanay",
    month: 8,
    dayStart: 23,
    dateSource: "lgu-mulanay-gov-ph",
    patronSaint: "Santa Rosa de Lima",
  },
  {
    barangay: "Bagupaye",
    municipality: "Mulanay",
    month: 5,
    datePrecision: "month",
    patronSaint: "Our Lady of Perpetual Help",
    dateSource: "lgu-mulanay-gov-ph",
  },
  {
    barangay: "Magsaysay",
    municipality: "Mulanay",
    month: 5,
    datePrecision: "month",
    dateSource: "lgu-mulanay-gov-ph",
  },
  {
    barangay: "Matataja",
    municipality: "Mulanay",
    month: 5,
    dayStart: 29,
    dateSource: "curated-online-matataja-mulanay-fb",
  },
  {
    barangay: "Bolo",
    municipality: "Mulanay",
    month: 5,
    dayStart: 10,
    dateSource: "curated-online-mulanay-mayor-fb",
  },
  {
    barangay: "Buenavista",
    municipality: "Mulanay",
    month: 6,
    dayStart: 13,
    patronSaint: "San Antonio de Padua",
    dateSource: "curated-online-buenavista-mulanay-fb",
  },
  {
    barangay: "Ibabang Cambuga",
    municipality: "Mulanay",
    month: 5,
    dayStart: 5,
    dateSource: "curated-online-ibabang-cambuga-mulanay-fb",
    note: "Sitio Malibago barangay fiesta tradition",
  },
  {
    barangay: "Ilayang Yuni",
    municipality: "Mulanay",
    month: 5,
    dayStart: 1,
    dateSource: "curated-online-ilayang-yuni-mulanay-fb",
  },
  {
    barangay: "Ibabang Yuni",
    municipality: "Mulanay",
    month: 5,
    dayStart: 3,
    dateSource: "curated-online-ibabang-yuni-mulanay-fb",
    note: "On-day Happy Fiesta Ibabang Yuni video (May 3, 2024; distinct from Ilayang Yuni May 1)",
  },
  {
    barangay: "Patabog",
    municipality: "Mulanay",
    month: 4,
    dayStart: 24,
    dateSource: "curated-online-mulanay-mayor-fb",
  },
  {
    barangay: "Latangan",
    municipality: "Mulanay",
    month: 4,
    dayStart: 22,
    dateSource: "curated-online-mulanay-mayor-fb",
    note: "Mayor on-day Maagang cha cha mula sa Latangan video (Apr 22, 2025)",
  },
  {
    barangay: "Canuyep",
    municipality: "Mulanay",
    month: 5,
    dayStart: 16,
    dateSource: "curated-online-canuyep-mulanay-fb",
  },
  {
    barangay: "Ilayang Cambuga (Mabini)",
    municipality: "Mulanay",
    month: 5,
    dayStart: 12,
    dateSource: "curated-online-mabini-mulanay-fb",
    note: "Brgy. Mabini Patronal Fiesta 2026 official FB page (BINGO event May 12, 2026)",
  },
  {
    barangay: "Sagongon",
    municipality: "Mulanay",
    month: 6,
    dayStart: 11,
    dateSource: "curated-online-mulanay-mayor-fb",
    note: "Mayor on-day Happy Patronal Fiesta Brgy. Sagongon photo (June 11, 2025)",
  },
  {
    barangay: "Pakiing",
    municipality: "Mulanay",
    month: 6,
    dayStart: 28,
    patronSaint: "Our Mother of Perpetual Help",
    dateSource: "parish-our-mother-of-perpetual-help-sumagonsong-mulanay",
    note: "OMPHS chapel in Sitio Sumagonsong, Brgy. Pakiing (ParishPH feast day June 28)",
  },
];
