/**
 * Oton, Iloilo — barangay feast days from verified provincial / parish / LGU sources.
 * Town poblacion barangays share the parish patronal fiesta (Immaculate Conception, Dec 8).
 * Sources: parishph.com; iloilo.gov.ph; web.archive.org/2021/oton.gov.ph barangay profiles;
 * facebook.com/OtonIloiloMyHometown chapel fiesta posts (dates from post text or feast-day captions).
 */
export const OTON_FIESTA_ENTRIES = [
  {
    barangay: "Sta. Rita",
    municipality: "Oton",
    month: 5,
    dayStart: 22,
    patronSaint: "Sta. Rita de Cascia",
    dateSource: "iloilo-provincial-gov-brgy-sta-rita-oton",
  },
  {
    barangay: "Poblacion East",
    municipality: "Oton",
    month: 12,
    dayStart: 8,
    patronSaint: "Immaculate Conception",
    dateSource: "parish-immaculate-conception-oton",
  },
  {
    barangay: "Poblacion North",
    municipality: "Oton",
    month: 12,
    dayStart: 8,
    patronSaint: "Immaculate Conception",
    dateSource: "parish-immaculate-conception-oton",
  },
  {
    barangay: "Poblacion South",
    municipality: "Oton",
    month: 12,
    dayStart: 8,
    patronSaint: "Immaculate Conception",
    dateSource: "parish-immaculate-conception-oton",
  },
  {
    barangay: "Poblacion West",
    municipality: "Oton",
    month: 12,
    dayStart: 8,
    patronSaint: "Immaculate Conception",
    dateSource: "parish-immaculate-conception-oton",
  },
  {
    barangay: "Santa Monica",
    municipality: "Oton",
    month: 8,
    dayStart: 27,
    patronSaint: "Saint Monica of Hippo",
    dateSource: "parish-sta-monica-oton",
  },
  {
    barangay: "Pakiad",
    municipality: "Oton",
    month: 9,
    dayStart: 22,
    patronSaint: "Sto. Tomas de Villanueva",
    dateSource: "lgu-oton-gov-ph-wayback-2021",
  },
  {
    barangay: "Abilay Sur",
    municipality: "Oton",
    month: 4,
    dayStart: 5,
    patronSaint: "San Vicente Ferrer",
    dateSource: "parish-immaculate-conception-oton-hometown-fb",
  },
  {
    barangay: "Cadinglian",
    municipality: "Oton",
    month: 4,
    dayStart: 1,
    patronSaint: "San Vicente Ferrer",
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Lambuyao",
    municipality: "Oton",
    month: 10,
    dayStart: 24,
    patronSaint: "Saint Raphael the Archangel",
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Caboloan Norte",
    municipality: "Oton",
    month: 5,
    dayStart: 15,
    patronSaint: "San Isidro Labrador",
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Alegre",
    municipality: "Oton",
    month: 5,
    dayStart: 13,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Rizal",
    municipality: "Oton",
    month: 5,
    dayStart: 13,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Botong",
    municipality: "Oton",
    month: 4,
    dayStart: 30,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Cabanbanan",
    municipality: "Oton",
    month: 3,
    dayStart: 3,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Buray",
    municipality: "Oton",
    month: 3,
    dayStart: 17,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Tuburan",
    municipality: "Oton",
    month: 3,
    dayStart: 17,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Cagbang",
    municipality: "Oton",
    month: 10,
    dayStart: 3,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Salngan",
    municipality: "Oton",
    month: 11,
    dayStart: 29,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Abilay Norte",
    municipality: "Oton",
    month: 2,
    dayStart: 24,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Tagbac Sur",
    municipality: "Oton",
    month: 2,
    dayStart: 24,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Tagbac Norte",
    municipality: "Oton",
    month: 3,
    dayStart: 2,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Batuan Ilaud",
    municipality: "Oton",
    month: 3,
    dayStart: 14,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Batuan Ilaya",
    municipality: "Oton",
    month: 2,
    dayStart: 2,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Bita Norte",
    municipality: "Oton",
    month: 3,
    dayStart: 13,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Sambaludan",
    municipality: "Oton",
    month: 1,
    dayStart: 29,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Caboloan Sur",
    municipality: "Oton",
    month: 3,
    dayStart: 26,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Polo Maestra Bita",
    municipality: "Oton",
    month: 3,
    dayStart: 26,
    dateSource: "curated-online-oton-hometown-fb",
  },
  {
    barangay: "Calam-Isan",
    municipality: "Oton",
    month: 8,
    dayStart: 16,
    patronSaint: "San Roque",
    dateSource: "curated-online-lagaw-ta-iloilo-fb",
  },
  {
    barangay: "Mambog",
    municipality: "Oton",
    month: 5,
    dayStart: 10,
    dateSource: "curated-online-oton-hometown-fb",
  },
];

/** Relative dates resolved at build time via parseDateFromRaw. */
export const OTON_FIESTA_RELATIVE_SCHEDULE = [
  {
    date: "2nd Saturday of February",
    barangay: "Galang",
    municipality: "Oton",
    patronSaint: "Nuestra Señora de Salvacion",
    dateSource: "lgu-oton-gov-ph-wayback-2021",
  },
  {
    date: "Last Sunday of February",
    barangay: "Trapiche",
    municipality: "Oton",
    patronSaint: "Señor Santo Niño",
    dateSource: "lgu-oton-gov-ph-wayback-2021",
  },
  {
    date: "2nd Sunday of February",
    barangay: "Turog-Turog",
    municipality: "Oton",
    patronSaint: "Nuestra Señora de la Candelaria",
    dateSource: "lgu-oton-gov-ph-wayback-2021",
  },
  {
    date: "3rd Saturday of February",
    barangay: "Bita Sur",
    municipality: "Oton",
    dateSource: "curated-online-oton-hometown-fb",
  },
];
