/**
 * Known LGU / parish barangay fiesta schedule sources.
 * Used by gap reports and fetch scripts to track backfill ROI.
 *
 * status: complete | partial | blocked | planned
 * format: html-table | html-article | curated-text | parish-text | relative-text
 */
export const LGU_SCHEDULE_REGISTRY = [
  {
    id: "santa-barbara-iloilo",
    municipality: "Santa Barbara",
    province: "Iloilo",
    url: "https://santa-barbara-iloilo.gov.ph/about/",
    format: "html-table",
    parser: "parseSantaBarbaraFiestaTable",
    status: "complete",
    dateSource: "lgu-santa-barbara-iloilo-gov-ph",
    notes: "60/60 barangays; Santa Barbara table parser",
  },
  {
    id: "cabatuan-parish",
    municipality: "Cabatuan",
    province: "Iloilo",
    url: "https://cabatuan.com/fiestaschedulesannicolasdetolentinoparish.html",
    format: "parish-text",
    parser: "buildCabatuanFiestaEntries",
    status: "complete",
    dateSource: "lgu-cabatuan-parish",
    notes: "San Nicolas 55/55 rows + OLC Jelicuon parish territory (14 barangays Feb 9) + Banguit Dec 29 IG; 68/68 complete",
  },
  {
    id: "dagupan",
    municipality: "City Of Dagupan",
    province: "Pangasinan",
    url: "https://www.dagupan.gov.ph/the-city/calendar-of-activities/",
    format: "html-table",
    parser: "parseDagupanFiestaTable",
    status: "complete",
    dateSource: "lgu-dagupan-gov-ph",
    notes: "31/31 dated: LGU table + ParishPH Bonuan Gueset Mar 25",
  },
  {
    id: "magallanes-sorsogon",
    municipality: "Magallanes",
    province: "Sorsogon",
    url: "https://magallanessorsogon.gov.ph/feast-day-and-patron-saints-of-the-barangay/",
    format: "html-table",
    parser: "parseMagallanesFiestaTable",
    status: "complete",
    dateSource: "lgu-magallanes-sorsogon",
  },
  {
    id: "siquijor-secrets",
    municipality: "Siquijor",
    province: "Siquijor",
    url: "https://siquijor-secrets.com/siquijor-fiestas/",
    format: "html-table",
    parser: "parseSiquijorFiestaTable",
    status: "complete",
    dateSource: "lgu-siquijor-secrets",
    notes: "135/135 schedule rows matched via PSGC aliases (Pulangyuta→Polangyuta, etc.)",
  },
  {
    id: "tarlac-city-curated",
    municipality: "City Of Tarlac (Capital)",
    province: "Tarlac",
    url: "https://tarlaccity.gov.ph/barangays/",
    format: "curated-text",
    parser: "TARLAC_FIESTA_ENTRIES",
    status: "complete",
    dateSource: "lgu-tarlac-city-gov-ph",
    notes: "76/76 dated via curated + Wayback LGU pages (De Lapaz slug → Dela Paz)",
  },
  {
    id: "tarlac-city-fetch",
    municipality: "City Of Tarlac (Capital)",
    province: "Tarlac",
    url: "https://tarlaccity.gov.ph/{slug}/",
    format: "html-article",
    parser: "parseTarlacBarangayPage",
    status: "complete",
    dateSource: "lgu-tarlac-city-gov-ph",
    notes: "Per-barangay pages; live site SSL/403; Wayback fallback (de-lapaz slug)",
  },
  {
    id: "maasin-city",
    municipality: "City Of Maasin (Capital)",
    province: "Southern Leyte",
    url: "http://www.maasincity.gov.ph/index.php/government/barangay",
    format: "html-directory",
    parser: "parseMaasinBarangayDirectory",
    status: "complete",
    dateSource: "lgu-maasin-city-directory",
    notes: "70/70 barangays on LGU directory (Pinaskohan → PSGC Pinascohan)",
  },
  {
    id: "maasin-articles",
    municipality: "City Of Maasin (Capital)",
    province: "Southern Leyte",
    url: "https://maasincity.gov.ph/index.php/barangays/brgy/14-barangays/{slug}",
    format: "html-article",
    parser: "parseMaasinBarangayArticle",
    status: "partial",
    dateSource: "lgu-maasin-city-gov-ph",
    notes: "Supplemental; 16/70 with feast text on article pages",
  },
  {
    id: "pinamungahan",
    municipality: "Pinamungahan",
    province: "Cebu",
    format: "curated-text",
    parser: "PINAMUNGAHAN_FIESTA_ENTRIES",
    status: "complete",
    dateSource: "lgu-pinamungajan-gov-ph",
  },
  {
    id: "bula-parish",
    municipality: "Bula",
    province: "Camarines Sur",
    format: "curated-text",
    parser: "BULA_FIESTA_ENTRIES",
    status: "complete",
    dateSource: "parish-saint-joseph-palsong-bula",
    notes: "ParishPH 3 parishes + LGU/parish FB batch; 33/33 PSGC dated (4 month-only: Pawili Sep, Lubgan Oct, Casugad May, Fabrica May); Causip Nov 11 SK/community FB; Panoypoyan Jul 25 Senior Santiago",
  },
  {
    id: "oton-curated",
    municipality: "Oton",
    province: "Iloilo",
    format: "curated-text",
    parser: "OTON_FIESTA_ENTRIES",
    status: "complete",
    dateSource: "parish-immaculate-conception-oton",
    notes: "37/37 curated rows matched; 37/37 PSGC dated; Bita Sur 3rd Saturday of February + Mambog May 10 from OtonIloiloMyHometown kapistahan schedule (posts 785520646937672, 573141318175607)",
  },
  {
    id: "san-pascual-batangas-mtcas",
    municipality: "San Pascual",
    province: "Batangas",
    url: "https://www.scribd.com/document/887672179/Barangay-Fiesta-2",
    format: "curated-text",
    parser: "SAN_PASCUAL_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-san-pascual-mtcas-scribd",
    notes: "29/29 barangays from a public copy attributed to San Pascual Municipal Tourism, Culture & The Arts Section.",
  },
  {
    id: "lagonoy-dahom",
    municipality: "Lagonoy",
    province: "Camarines Sur",
    url: "https://dahomlagonoy.weebly.com/dl-blogs/barangay-fiesta",
    format: "curated-text",
    parser: "LAGONOY_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-lagonoy-dahom",
    notes: "38/38 barangays; AGCATA mapped to PSGC Agpo-Camagong-Tabog.",
  },
  {
    id: "santa-maria-bulacan-clup",
    municipality: "Santa Maria",
    province: "Bulacan",
    url: "https://www.scribd.com/document/744110354/Comprehensive-Land-Use-Plan-of-Santa-Maria-2006-2015-1",
    format: "curated-text",
    parser: "SANTA_MARIA_BULACAN_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-santa-maria-bulacan-clup",
    notes: "24/24 barangays from CLUP Table LU-24; Sto. Tomas mapped to PSGC Tabing Bakod.",
  },
  {
    id: "san-vicente-palawan-clup",
    municipality: "San Vicente",
    province: "Palawan",
    url: "https://www.scribd.com/document/510524031/LA-SERENE",
    format: "curated-text",
    parser: "SAN_VICENTE_PALAWAN_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-san-vicente-palawan-clup",
    notes: "10/10 barangays from municipal tourism / CLUP barangay fiesta table.",
  },
  {
    id: "ubay-wikipedia-barangay-table",
    municipality: "Ubay",
    province: "Bohol",
    url: "https://en.wikipedia.org/wiki/Ubay,_Bohol#Barangays",
    format: "curated-text",
    parser: "UBAY_WIKIPEDIA_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "wikipedia-ubay-bohol-barangay-table",
    notes: "44/44 barangays from the Wikipedia barangay table Date of Fiesta column.",
  },
  {
    id: "masantol-mpdo",
    municipality: "Masantol",
    province: "Pampanga",
    url: "https://www.scribd.com/document/995540556/Brgy-Fiesta",
    format: "curated-text",
    parser: "MASANTOL_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-masantol-mpdo-scribd",
    notes: "26/26 barangays from a public copy attributed to the Municipal Planning & Development Coordinator.",
  },
  {
    id: "misamis-oriental-2nd-district",
    municipality: "Jasaan",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270867869/Municipalities-Feast-Date-2nd-District",
    format: "curated-text",
    parser: "JASAAN_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-misamis-oriental-2nd-district-scribd",
    notes: "15/15 Jasaan barangays from Misamis Oriental 2nd District feast-date table.",
  },
  {
    id: "misamis-oriental-2nd-district-villanueva",
    municipality: "Villanueva",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270867869/Municipalities-Feast-Date-2nd-District",
    format: "curated-text",
    parser: "VILLANUEVA_MISOR_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-misamis-oriental-2nd-district-scribd",
    notes: "11/11 Villanueva barangays from Misamis Oriental 2nd District feast-date table.",
  },
  {
    id: "misamis-oriental-2nd-district-tagoloan",
    municipality: "Tagoloan",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270867869/Municipalities-Feast-Date-2nd-District",
    format: "curated-text",
    parser: "TAGOLOAN_MISOR_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-misamis-oriental-2nd-district-scribd",
    notes: "10/10 Tagoloan barangays from Misamis Oriental 2nd District feast-date table.",
  },
  {
    id: "misamis-oriental-2nd-district-opol",
    municipality: "Opol",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270867869/Municipalities-Feast-Date-2nd-District",
    format: "curated-text",
    parser: "OPOL_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-misamis-oriental-2nd-district-scribd",
    notes: "14/14 Opol barangays from Misamis Oriental 2nd District feast-date table.",
  },
  {
    id: "misamis-oriental-1st-district-magsaysay",
    municipality: "Magsaysay (Linugos)",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270868638/Municipalities-Feast-Date-1st-District",
    format: "curated-text",
    parser: "MAGSAYSAY_MISOR_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-misamis-oriental-1st-district-scribd",
    notes: "25/25 barangays from Misamis Oriental 1st District feast-date table.",
  },
  {
    id: "misamis-oriental-1st-district-balingoan",
    municipality: "Balingoan",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270868638/Municipalities-Feast-Date-1st-District",
    format: "curated-text",
    parser: "BALINGOAN_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-misamis-oriental-1st-district-scribd",
    notes: "9/9 barangays from Misamis Oriental 1st District feast-date table.",
  },
  {
    id: "misamis-oriental-1st-district-kinoguitan",
    municipality: "Kinoguitan",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270868638/Municipalities-Feast-Date-1st-District",
    format: "curated-text",
    parser: "KINOGUITAN_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-misamis-oriental-1st-district-scribd",
    notes: "15/15 barangays from Misamis Oriental 1st District feast-date table.",
  },
  {
    id: "misamis-oriental-1st-district-sugbongcogon",
    municipality: "Sugbongcogon",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270868638/Municipalities-Feast-Date-1st-District",
    format: "curated-text",
    parser: "SUGBONGCOGON_FIESTA_SCHEDULE",
    status: "partial",
    dateSource: "lgu-misamis-oriental-1st-district-scribd",
    notes: "8/10 barangays; Kaulayanan is listed with no fiesta and the Mimbuahan date row is ambiguous in OCR.",
  },
  {
    id: "misamis-oriental-1st-district-talisayan",
    municipality: "Talisayan",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270868638/Municipalities-Feast-Date-1st-District",
    format: "curated-text",
    parser: "TALISAYAN_FIESTA_SCHEDULE",
    status: "complete",
    dateSource: "lgu-misamis-oriental-1st-district-scribd",
    notes: "18/18 barangays from Misamis Oriental 1st District feast-date table.",
  },
  {
    id: "misamis-oriental-1st-district-medina",
    municipality: "Medina",
    province: "Misamis Oriental",
    url: "https://www.scribd.com/doc/270868638/Municipalities-Feast-Date-1st-District",
    format: "curated-text",
    parser: "MEDINA_FIESTA_SCHEDULE",
    status: "partial",
    dateSource: "lgu-misamis-oriental-1st-district-scribd",
    notes: "15/19 barangays; only rows with unambiguous barangay/date pairings were imported.",
  },
  {
    id: "miagao-curated",
    municipality: "Miagao",
    province: "Iloilo",
    format: "curated-text",
    parser: "MIAGAO_FIESTA_ENTRIES",
    status: "partial",
    dateSource: "lgu-miagao-gov-ph",
    notes: "97/119 dated: miagao.tripod.com profiles + patron-saint-calendar-profile inference",
  },
  {
    id: "iloilo-city-curated",
    municipality: "City Of Iloilo (Capital)",
    province: "Iloilo",
    format: "curated-text",
    parser: "ILOILO_CITY_FIESTA_ENTRIES",
    status: "partial",
    dateSource: "curated-online-iloilo-city-youtube",
    notes: "46/180 dated: on-day YouTube + TheOldChurches (Luna La Paz Jun 20, Sambag, South Fundidor, Lopez Jaena Norte) and prior curated rows",
  },
  {
    id: "mulanay-curated",
    municipality: "Mulanay",
    province: "Quezon",
    format: "curated-text",
    parser: "MULANAY_FIESTA_ENTRIES",
    status: "complete",
    dateSource: "lgu-mulanay-gov-ph",
    notes: "28/28 dated from LGU profiles + mayor/community FB + OMPHS Sumagonsong parish (Pakiing Jun 28); Latangan Apr 22 mayor on-day cha-cha video",
  },
  {
    id: "ormoc-curated",
    municipality: "Ormoc City",
    province: "Leyte",
    format: "curated-text",
    parser: "ORMOC_FIESTA_ENTRIES",
    status: "partial",
    dateSource: "parish-ormoc-city",
    notes: "ParishPH + Ormoc Cultural Mapping ICH; 8/110 dated (Valencia, San Pablo Simangan, Cogon, Ipil, Manlilinao, Curva, Linao, Punta)",
  },
  {
    id: "iloilo-province-theoldchurches",
    municipality: "Iloilo (multi-municipality)",
    province: "Iloilo",
    format: "curated-text",
    parser: "ILOILO_PROVINCE_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-iloilo-province",
    notes: "TheOldChurches 1:1 parish address matches: Batad, Dingle, Calinog (2), Pototan (4), Janiuay, Maasin Iloilo, Passi (2), San Joaquin (2), Alimodian, Leon, Barotac Nuevo, Banate, Barotac Viejo",
  },
  {
    id: "leyte-theoldchurches",
    municipality: "Leyte (multi-municipality)",
    province: "Leyte",
    format: "curated-text",
    parser: "LEYTE_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-leyte",
    notes: "TheOldChurches 1:1 matches: Baybay (3), Bato, Matalom, Hilongos, Palo, Inopacan, Abuyog (2), Ormoc Libertad, Carigara, Alangalang, Tolosa, Tacloban New Kawayan, Calubian, Tanauan, Albuera",
  },
  {
    id: "cebu-theoldchurches",
    municipality: "Cebu (multi-municipality)",
    province: "Cebu",
    format: "curated-text",
    parser: "CEBU_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-cebu",
    notes: "TheOldChurches 89 barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "capiz-theoldchurches",
    municipality: "Capiz (multi-municipality)",
    province: "Capiz",
    format: "curated-text",
    parser: "CAPIZ_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-capiz",
    notes: "TheOldChurches 36 barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "negros-occidental-theoldchurches",
    municipality: "Negros Occidental (multi-municipality)",
    province: "Negros Occidental",
    format: "curated-text",
    parser: "NEGROS_OCCIDENTAL_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-negros-occidental",
    notes: "TheOldChurches 66 barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "aklan-theoldchurches",
    municipality: "Aklan (multi-municipality)",
    province: "Aklan",
    format: "curated-text",
    parser: "AKLAN_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-aklan",
    notes: "TheOldChurches 7 barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "bohol-theoldchurches",
    municipality: "Bohol (multi-municipality)",
    province: "Bohol",
    format: "curated-text",
    parser: "BOHOL_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-bohol",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "camarines-sur-theoldchurches",
    municipality: "Camarines Sur (multi-municipality)",
    province: "Camarines Sur",
    format: "curated-text",
    parser: "CAMARINES_SUR_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-camarines-sur",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "negros-oriental-theoldchurches",
    municipality: "Negros Oriental (multi-municipality)",
    province: "Negros Oriental",
    format: "curated-text",
    parser: "NEGROS_ORIENTAL_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-negros-oriental",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "samar-theoldchurches",
    municipality: "Samar (multi-municipality)",
    province: "Samar",
    format: "curated-text",
    parser: "SAMAR_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-samar",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "eastern-samar-theoldchurches",
    municipality: "Eastern Samar (multi-municipality)",
    province: "Eastern Samar",
    format: "curated-text",
    parser: "EASTERN_SAMAR_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-eastern-samar",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "northern-samar-theoldchurches",
    municipality: "Northern Samar (multi-municipality)",
    province: "Northern Samar",
    format: "curated-text",
    parser: "NORTHERN_SAMAR_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-northern-samar",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "southern-leyte-theoldchurches",
    municipality: "Southern Leyte (multi-municipality)",
    province: "Southern Leyte",
    format: "curated-text",
    parser: "SOUTHERN_LEYTE_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-southern-leyte",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "antique-theoldchurches",
    municipality: "Antique (multi-municipality)",
    province: "Antique",
    format: "curated-text",
    parser: "ANTIQUE_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-antique",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "romblon-theoldchurches",
    municipality: "Romblon (multi-municipality)",
    province: "Romblon",
    format: "curated-text",
    parser: "ROMBLON_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-romblon",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "guimaras-theoldchurches",
    municipality: "Guimaras (multi-municipality)",
    province: "Guimaras",
    format: "curated-text",
    parser: "GUIMARAS_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-guimaras",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "camarines-norte-theoldchurches",
    municipality: "Camarines Norte (multi-municipality)",
    province: "Camarines Norte",
    format: "curated-text",
    parser: "CAMARINES_NORTE_THEOLDCHURCHES_ENTRIES",
    status: "partial",
    dateSource: "theoldchurches-camarines-norte",
    notes: "TheOldChurches barangay parish pages with address-level 1:1 PSGC matches",
  },
  {
    id: "pangasinan-parish-ph",
    municipality: "Pangasinan (multi-municipality)",
    province: "Pangasinan",
    format: "curated-text",
    parser: "PANGASINAN_PARISH_FIESTA_ENTRIES",
    status: "partial",
    dateSource: "parish-ph-pangasinan",
    notes: "ParishPH 1:1 matches: Dagupan Bonuan Gueset (31/31), Binmaley, Calasiao, Mangaldan (2), Lingayen, Malasiqui (2), Santa Barbara Pangasinan, San Carlos (2), Mapandan, Bayambang (3), Urbiztondo, Bautista",
  },
  {
    id: "leyte-parish-ph",
    municipality: "Leyte (multi-municipality)",
    province: "Leyte",
    format: "curated-text",
    parser: "LEYTE_PARISH_FIESTA_ENTRIES",
    status: "partial",
    dateSource: "parish-ph-leyte",
    notes: "ParishPH 1:1 matches: Palo (2), Tanauan, Abuyog, Tolosa, Capoocan, Kananga, Villaba, Isabel, Burauen, Dagami, Palompon (2), Babatngon",
  },
  {
    id: "dulag-parish",
    municipality: "Dulag",
    province: "Leyte",
    format: "curated-text",
    parser: "DULAG_FIESTA_ENTRIES",
    status: "partial",
    dateSource: "parish-dulag-leyte",
    notes: "ParishPH 3/34 barangays (Cabacungan, San Jose, Sungi Pob.)",
  },
  {
    id: "carigara-parish",
    municipality: "Carigara",
    province: "Leyte",
    format: "curated-text",
    parser: "CARIGARA_FIESTA_ENTRIES",
    status: "partial",
    dateSource: "parish-carigara-leyte",
    notes: "ParishPH 1/49 barangays (Jugaban Pob.)",
  },
  {
    id: "tacloban-city-curated",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    format: "curated-text",
    parser: "TACLOBAN_FIESTA_ENTRIES",
    status: "partial",
    dateSource: "parish-tacloban-city",
    notes: "ParishPH 1:1 barangay matches; 15/138 dated incl. patron-saint + Abucay, Apitong, Bagacay, Tigbao, San Jose (83)",
  },
  {
    id: "tacloban-city",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    url: "https://tacloban.gov.ph/barangays/",
    format: "html-article",
    parser: null,
    status: "blocked",
    dateSource: "lgu-tacloban-gov-ph",
    notes: "Legacy row; LGU site 403 — use tacloban-city-curated (ParishPH) for barangay dates",
  },
];

/** Registry rows keyed by municipality (+ province when ambiguous). */
export function registryByMunicipalityKey() {
  const map = new Map();
  for (const row of LGU_SCHEDULE_REGISTRY) {
    const key = `${row.province}::${row.municipality}`;
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(row);
  }
  return map;
}
