/**
 * City of Tacloban, Leyte — barangay feast days from ParishPH parish records.
 * Only barangays with a 1:1 PSGC match to the parish location are included.
 */
export const TACLOBAN_FIESTA_ENTRIES = [
  {
    barangay: "Barangay 91 (Abucay)",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    month: 12,
    dayStart: 12,
    patronSaint: "Our Lady of Guadalupe",
    dateSource: "parish-our-lady-of-guadalupe-abucay-tacloban",
    note: "ParishPH Our Lady of Guadalupe Parish, Brgy. Abucay",
  },
  {
    barangay: "Barangay 92 (Apitong)",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    month: 6,
    dayStart: 26,
    patronSaint: "Saint Josemaria Escriva",
    dateSource: "parish-st-josemaria-escriva-apitong-tacloban",
    note: "ParishPH St. Josemaria Escriva Mission Station, Brgy. Apitong",
  },
  {
    barangay: "Barangay 93 (Bagacay)",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    month: 2,
    dayStart: 2,
    patronSaint: "Virgen de la Candelaria",
    dateSource: "parish-virgen-candelaria-bagacay-tacloban",
    note: "ParishPH Virgen de la Candelaria Mission Station, Brgy. Bagacay",
  },
  {
    barangay: "Barangay 94 (Tigbao)",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    month: 8,
    dayStart: 2,
    dateSource: "parish-blessed-sacrament-tigbao-tacloban",
    note: "ParishPH Archdiocesan Shrine and Parish of the Blessed Sacrament, Brgy. Tigbao",
  },
  {
    barangay: "Barangay 83 (San Jose)",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    month: 5,
    dayStart: 25,
    patronSaint: "St. Joseph",
    dateSource: "parish-san-jose-tacloban",
    note: "ParishPH San Jose Parish, Brgy. San Jose (central San Jose barangay 83; parish seat)",
  },
  {
    barangay: "Barangay 86",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    month: 5,
    dayStart: 25,
    patronSaint: "St. Joseph",
    dateSource: "parish-san-jose-tacloban-barangay-86",
    note: "ParishPH San Jose Parish — feast May 25; parish address Barangay 86 San Jose, Tacloban City",
  },
  {
    barangay: "Nula-Tula (Bgys. 3 & 3a)",
    municipality: "City Of Tacloban (Capital)",
    province: "Leyte",
    month: 10,
    dayStart: 28,
    patronSaint: "St. Jude Thaddeus",
    dateSource: "parish-st-jude-phhc-nula-tula-tacloban",
    note: "ParishPH St. Jude Thaddeus Parish (PHHC) — feast October 28; Nula-Tula, Tacloban City",
  },
];
