/**
 * City of Tarlac barangay feast days from tarlaccity.gov.ph barangay pages.
 */
export const TARLAC_FIESTA_ENTRIES = [
  {
    barangay: "San Sebastian",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 20,
    patronSaint: "Saint Sebastian",
  },
  {
    barangay: "Poblacion",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 20,
    patronSaint: "Saint Sebastian",
  },
  {
    barangay: "Mabini",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 13,
    dayEnd: 20,
    patronSaint: "Saint Sebastian",
  },
  {
    barangay: "Sto. Niño",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 14,
    dayEnd: 15,
    patronSaint: "Sto. Niño",
  },
  {
    barangay: "Lourdes",
    municipality: "City Of Tarlac",
    month: 2,
    dayStart: 10,
    dayEnd: 11,
    patronSaint: "Our Lady of Lourdes",
  },
  {
    barangay: "San Jose",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 18,
    dayEnd: 19,
    patronSaint: "Saint Joseph",
  },
  {
    barangay: "Aguso",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 19,
    patronSaint: "Saint Joseph",
  },
  {
    barangay: "Balibago I",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 23,
    dayEnd: 24,
    patronSaint: "Sagrada Familia",
  },
  {
    barangay: "Sapang Maragul",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 26,
    patronSaint: "Saint Augustine",
  },
  {
    barangay: "San Vicente",
    municipality: "City Of Tarlac",
    month: 4,
    dayStart: 4,
    dayEnd: 5,
    patronSaint: "Saint Vincent de Ferrer",
  },
  {
    barangay: "Dolores",
    municipality: "City Of Tarlac",
    month: 4,
    dayStart: 1,
    dayEnd: 2,
    patronSaint: "San Vicente de Ferrer",
  },
  {
    barangay: "Suizo",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 1,
    patronSaint: "Saint Michael the Archangel",
  },
  {
    barangay: "Sto. Cristo",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 2,
    dayEnd: 3,
    patronSaint: "Apung Sto. Cristo",
  },
  {
    barangay: "Paraiso",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 12,
    dayEnd: 13,
    patronSaint: "St. Andrew",
  },
  {
    barangay: "San Isidro",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 15,
    patronSaint: "San Isidro Labrador",
  },
  {
    barangay: "Sta. Cruz",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 18,
    dayEnd: 19,
    patronSaint: "Sto. Cristo",
  },
  {
    barangay: "San Roque",
    municipality: "City Of Tarlac",
    month: 8,
    dayStart: 16,
    patronSaint: "San Roque",
  },
  {
    barangay: "San Rafael",
    municipality: "City Of Tarlac",
    month: 10,
    dayStart: 24,
    patronSaint: "San Raphael the Archangel",
  },
  {
    barangay: "Cut-Cut I",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 13,
    dayEnd: 20,
    patronSaint: "Saint Sebastian",
  },
  {
    barangay: "Ligtasan",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 23,
    patronSaint: "Christ the King",
  },
  {
    barangay: "Maliwalo",
    municipality: "City Of Tarlac",
    month: 2,
    dayStart: 11,
    patronSaint: "Our Lady of Lourdes",
  },
  {
    barangay: "Culipat",
    municipality: "City Of Tarlac",
    month: 4,
    dayStart: 5,
    patronSaint: "Saint Vincent de Ferrer",
  },
  {
    barangay: "Balingcanaway",
    municipality: "City Of Tarlac",
    month: 4,
    dayStart: 5,
    patronSaint: "Saint Francis of Assisi",
  },
  {
    barangay: "San Manuel",
    municipality: "City Of Tarlac",
    month: 4,
    dayStart: 5,
    patronSaint: "Saint Vincent de Ferrer",
  },
  {
    barangay: "Banaba",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 4,
    dayEnd: 5,
    patronSaint: "Sto. Cristo",
  },
  {
    barangay: "Binauganan",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 15,
    patronSaint: "San Isidro Labrador",
  },
  {
    barangay: "Amucao",
    municipality: "City Of Tarlac",
    month: 9,
    dayStart: 27,
    patronSaint: "Saint Vincent de Paul",
  },
  {
    barangay: "Matatalaib",
    municipality: "City Of Tarlac",
    month: 9,
    dayStart: 24,
    patronSaint: "Nuestra Señora de la Merced",
  },
  {
    barangay: "Cut-Cut Ii",
    municipality: "City Of Tarlac",
    month: 11,
    dayStart: 25,
    patronSaint: "Saint Catherine of Alexandria",
  },
  {
    barangay: "Capehan",
    municipality: "City Of Tarlac",
    month: 10,
    dayStart: 30,
    patronSaint: "Our Lady of Fatima",
  },
  {
    barangay: "Bora",
    municipality: "City Of Tarlac",
    month: 12,
    dayStart: 31,
    patronSaint: "Saint Lorenzo Ruiz",
  },
  {
    barangay: "Buhilit",
    municipality: "City Of Tarlac",
    month: 4,
    dayStart: 9,
    dayEnd: 10,
  },
  {
    barangay: "Central",
    municipality: "City Of Tarlac",
    month: 2,
    dayStart: 10,
    dayEnd: 11,
    patronSaint: "Our Lady of Lourdes",
  },
  {
    barangay: "Dalayap",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 18,
    dayEnd: 19,
    patronSaint: "Saint Joseph",
  },
  {
    barangay: "Asturias",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 18,
    dayEnd: 19,
    patronSaint: "Saint Joseph",
  },
  {
    barangay: "Sinait",
    municipality: "City Of Tarlac",
    month: 4,
    dayStart: 23,
    patronSaint: "Birhen Dolorosa",
  },
  {
    barangay: "Maligaya",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 11,
    dayEnd: 12,
    patronSaint: "Holy Family",
  },
  {
    barangay: "Tibag",
    municipality: "City Of Tarlac",
    month: 12,
    dayStart: 7,
    dayEnd: 8,
    patronSaint: "Immaculate Conception",
  },
  {
    barangay: "Mapalad",
    municipality: "City Of Tarlac",
    month: 11,
    dayStart: 7,
  },
  {
    barangay: "Balanti",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 26,
    patronSaint: "Our Lady of Lourdes",
  },
  {
    barangay: "Care",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 15,
    dayEnd: 16,
  },
  {
    barangay: "Laoang",
    municipality: "City Of Tarlac",
    month: 11,
    dayStart: 26,
    patronSaint: "Mama Delos Remedios",
  },
  {
    barangay: "Mapalacsiao",
    municipality: "City Of Tarlac",
    month: 12,
    dayStart: 8,
    patronSaint: "Immaculate Conception",
  },
  {
    barangay: "Tibagan",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 9,
    patronSaint: "Black Nazarene",
  },
  {
    barangay: "Balibago Ii",
    municipality: "City Of Tarlac",
    month: 12,
    dayStart: 9,
    dayEnd: 10,
    patronSaint: "Sagrada Familia",
  },
  {
    barangay: "Tariji",
    municipality: "City Of Tarlac",
    month: 7,
    dayStart: 16,
    patronSaint: "Our Lady of Mt. Carmel",
    dateSource: "parish-our-lady-mt-carmel-tariji",
  },
  {
    barangay: "Atioc",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 9,
    patronSaint: "Nuestro Padre Jesus Nazareno",
    dateSource: "diocese-of-tarlac-directory",
  },
  {
    barangay: "Armenia",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 8,
    patronSaint: "St. Michael the Archangel",
    dateSource: "diocese-of-tarlac-directory",
  },
  {
    barangay: "Carangian",
    municipality: "City Of Tarlac",
    month: 8,
    dayStart: 23,
    patronSaint: "Santa Rosa de Lima",
    dateSource: "lgu-tarlac-city-gov-ph-curated",
  },
  {
    barangay: "Alvindia Segundo",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 24,
    dayEnd: 25,
    patronSaint: "Saint Paul",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Balete",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 15,
    patronSaint: "San Isidro Labrador",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Batang-Batang",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 25,
    patronSaint: "Saint Francis of Assisi",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Calingcuan",
    municipality: "City Of Tarlac",
    month: 2,
    dayStart: 11,
    patronSaint: "Our Lady of Lourdes",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Matadero",
    municipality: "City Of Tarlac",
    month: 6,
    dayStart: 23,
    dayEnd: 24,
    patronSaint: "Saint John the Baptist",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Sepung Calzada",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 23,
    dayEnd: 24,
    patronSaint: "Nuestra Señora dela Paz",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Trinidad",
    municipality: "City Of Tarlac",
    month: 5,
    dayStart: 14,
    dayEnd: 15,
    patronSaint: "San Isidro Labrador",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Ungot",
    municipality: "City Of Tarlac",
    month: 3,
    dayStart: 19,
    patronSaint: "Saint Joseph",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Villa Bacolor",
    municipality: "City Of Tarlac",
    month: 12,
    dayStart: 8,
    patronSaint: "Immaculate Conception",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
  {
    barangay: "Dela Paz",
    municipality: "City Of Tarlac",
    month: 1,
    dayStart: 23,
    dayEnd: 24,
    patronSaint: "Nuestra Señora dela Paz",
    dateSource: "lgu-tarlac-city-gov-ph",
  },
];

/** Relative dates from tarlaccity.gov.ph (Buenavista: 2nd or 3rd week of March). */
export const TARLAC_RELATIVE_FIESTA_SCHEDULE = [
  {
    date: "3rd week of March",
    barangay: "Buenavista",
    patronSaint: "Saint Dominic",
  },
  {
    date: "Last Sunday of December",
    barangay: "Baras-Baras",
    patronSaint: "Santa Barbara",
  },
  {
    date: "Last Sunday of January",
    barangay: "Sapang Tagalog",
    patronSaint: "Holy Family",
  },
  {
    date: "First Saturday of May",
    barangay: "Burot",
    patronSaint: "Apung Sto. Cristo",
  },
  {
    date: "Last week of February",
    barangay: "Bantog",
    patronSaint: "Sta. Corazon de Jesus",
  },
  {
    date: "First Sunday of February",
    barangay: "Salapungan",
    patronSaint: "Saint Paul",
  },
];
